// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthZGLzy8EkqgqCnx422tZ3YDCI9cXiSI',
    appId: '1:114077624121:web:e1a721b299ebf16dfa6ae8',
    messagingSenderId: '114077624121',
    projectId: 'cornerapp-389112',
    authDomain: 'cornerapp-389112.firebaseapp.com',
    databaseURL: 'https://cornerapp-389112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cornerapp-389112.appspot.com',
    measurementId: 'G-ZZKM3VMNPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhwhJmk4YlFUvoSAHWZesYKVySoEJFQ4E',
    appId: '1:114077624121:android:8730762db0e3fbd9fa6ae8',
    messagingSenderId: '114077624121',
    projectId: 'cornerapp-389112',
    databaseURL: 'https://cornerapp-389112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cornerapp-389112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kKRK-Mo7O6UQGP3lHkNH6UgqTu860Kg',
    appId: '1:114077624121:ios:b529b9c7d7817d21fa6ae8',
    messagingSenderId: '114077624121',
    projectId: 'cornerapp-389112',
    databaseURL: 'https://cornerapp-389112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cornerapp-389112.appspot.com',
    iosBundleId: 'cornerstone.CornerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1kKRK-Mo7O6UQGP3lHkNH6UgqTu860Kg',
    appId: '1:114077624121:ios:cbab5cd4d23c0ad5fa6ae8',
    messagingSenderId: '114077624121',
    projectId: 'cornerapp-389112',
    databaseURL: 'https://cornerapp-389112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cornerapp-389112.appspot.com',
    iosClientId: '114077624121-g6qfqji8ak63ilfsb7dn5t556h65uvvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.CornerApp',
  );
}
